---
- name: Setup requirements
  hosts: migrator
  tasks:
    - name: Copy clouds.yaml to os-migrate data dir
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.config/openstack/clouds.yaml"
        dest: "{{ os_migrate_vmw_data_dir }}"
        mode: "0644"
      when: not already_deploy_conversion_host

    - name: Make sure required package are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        use_backend: dnf4
      become: true
      with_items:
        - python3
        - python3-pip
      when: not runner_from_aee | default(false)

    - name: Install openstacksdk
      ansible.builtin.pip:
        name: "{{ item }}"
      become: true
      with_items:
        - openstacksdk>1.0.0
        - requests
        - pyVim
        - pyVmomi
        - aiohttp
      when: not runner_from_aee | default(false)

    - name: Add custom host entries to in-memory hosts mapping
      ansible.builtin.add_host:
        name: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        groups: custom_hosts_group
      loop: "{{ custom_hosts | default([]) }}"
      when: custom_hosts is defined and custom_hosts | length > 0
      changed_when: false

    - name: Display custom hosts configuration
      ansible.builtin.debug:
        msg: |
          Custom host entries configured in Ansible inventory:
          {% for host in custom_hosts | default([]) %}
          - {{ host.hostname }}: {{ host.ip }}
          {% endfor %}
          
          Note: For AAP/Execution Environments, configure these in:
          1. Job Template -> Extra Vars -> Add container_options
          2. Execution Environment definition with podman_extra_args
          Example:
            container_options:
              extra_hosts:
          {% for host in custom_hosts | default([]) %}
                - "{{ host.hostname }}:{{ host.ip }}"
          {% endfor %}
      when: custom_hosts is defined and custom_hosts | length > 0

    - name: Display custom DNS configuration
      ansible.builtin.debug:
        msg: |
          Custom DNS servers requested:
          {% for dns in custom_dns_servers | default([]) %}
          - {{ dns }}
          {% endfor %}
          
          Note: For AAP/Execution Environments, configure these in:
          1. Job Template -> Extra Vars -> Add container_options
          2. Execution Environment definition
          Example:
            container_options:
              dns:
          {% for dns in custom_dns_servers | default([]) %}
                - "{{ dns }}"
          {% endfor %}
      when: custom_dns_servers is defined and custom_dns_servers | length > 0
