---
- name: Setup requirements
  hosts: migrator
  tasks:
    - name: Copy clouds.yaml to os-migrate data dir
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.config/openstack/clouds.yaml"
        dest: "{{ os_migrate_vmw_data_dir }}"
        mode: "0644"
      when: not already_deploy_conversion_host

    - name: Make sure required package are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        use_backend: dnf4
      become: true
      with_items:
        - python3
        - python3-pip
      when: not runner_from_aee | default(false)

    - name: Install openstacksdk
      ansible.builtin.pip:
        name: "{{ item }}"
      become: true
      with_items:
        - openstacksdk>1.0.0
        - requests
        - pyVim
        - pyVmomi
        - aiohttp
      when: not runner_from_aee | default(false)

    - name: Read current /etc/hosts content
      ansible.builtin.slurp:
        src: /etc/hosts
      register: current_hosts
      when: custom_hosts is defined and custom_hosts | length > 0

    - name: Add custom hosts to /etc/hosts
      ansible.builtin.copy:
        content: |
          {{ current_hosts.content | b64decode }}
          # BEGIN ANSIBLE MANAGED BLOCK - Custom Hosts
          {% for host in custom_hosts | default([]) %}
          {{ host.ip }} {{ host.hostname }}
          {% endfor %}
          # END ANSIBLE MANAGED BLOCK - Custom Hosts
        dest: /etc/hosts
        unsafe_writes: true
        mode: '0644'
      when: custom_hosts is defined and custom_hosts | length > 0

    - name: Read current /etc/resolv.conf content
      ansible.builtin.slurp:
        src: /etc/resolv.conf
      register: current_resolv
      when: custom_dns_servers is defined and custom_dns_servers | length > 0

    - name: Configure DNS servers in /etc/resolv.conf
      ansible.builtin.copy:
        content: |
          {% for dns in custom_dns_servers | default([]) %}
          nameserver {{ dns }}
          {% endfor %}
          {{ current_resolv.content | b64decode }}
        dest: /etc/resolv.conf
        unsafe_writes: true
        mode: '0644'
      when: custom_dns_servers is defined and custom_dns_servers | length > 0
